services:

  python:
    build:
      context: ../python
      dockerfile: ../.devcontainer/python/Dockerfile
    volumes:
      - ../python:/workspace:cached
    command: sleep infinity
    ports:
      - "5001:5000"
  
  angular:
    build:
      context: ../angular
      dockerfile: ../.devcontainer/angular/Dockerfile
    volumes:
      - ../angular:/workspace:cached
    command: sleep infinity
    ports:
      - "4200:4200"

  kubernetes:
    build:
      context: ../kubernetes
      dockerfile: ../.devcontainer/kubernetes/Dockerfile
    volumes:
      - ../kubernetes:/workspace:cached
    command: sleep infinity

  terraform:
    build:
      context: ../terraform
      dockerfile: ../.devcontainer/terraform/Dockerfile
    volumes:
      - ../terraform:/workspace:cached
    command: sleep infinity