services:

  python:
    build:
      context: ../python
      dockerfile: ../.devcontainer/python/Dockerfile
    volumes:
      - ../python:/workspace:cached
    command: sleep infinity
    ports:
      - "5001:5000"
  
  angular:
    build:
      context: ../angular
      dockerfile: ../.devcontainer/angular/Dockerfile
    volumes:
      - ../angular:/workspace:cached
    command: sleep infinity
    ports:
      - "4200:4200"

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  kubernetes:
    build:
      context: ../kubernetes
      dockerfile: ../.devcontainer/kubernetes/Dockerfile
    volumes:
      - ../kubernetes:/workspace:cached
    command: sleep infinity

  terraform:
    build:
      context: ../terraform
      dockerfile: ../.devcontainer/terraform/Dockerfile
    volumes:
      - ../terraform:/workspace:cached
    command: sleep infinity