services:
  python-backend:
    build:
      context: ../python-backend
      dockerfile: ../.devcontainer/python-backend/Dockerfile
    volumes:
      - ../python-backend:/workspace:cached
    command: sleep infinity
    ports:
      - "5000:5000"
  
  angular-frontend:
    build:
      context: ../angular-frontend
      dockerfile: ../.devcontainer/angular-frontend/Dockerfile
    volumes:
      - ../angular-frontend:/workspace:cached
    command: sleep infinity
    ports:
      - "4200:4200"
